ALTER TABLE tools
  ADD COLUMN IF NOT EXISTS vendor_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS api_status text NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS api_docs_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS api_auth_method text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS api_notes text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pricing_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS support_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS security_notes text NOT NULL DEFAULT '';
